### ISSUE TITLE
lens placeholder images not loading

### ISSUE THREAD

**Issue by dingerr** [ptrumpis/snap-camera-server#103]
Please make sure the **Wiki** and **Discussions** section does not solve your problem:
- https://github.com/ptrumpis/snap-camera-server/wiki
- https://github.com/ptrumpis/snap-camera-server/discussions

If you are having technical difficulties please provide the following information:
**System (please complete the following information):**
 - OS: [e.g. Windows, Mac OS] Windows 11
 - Server Version: [e.g. 2.0.6, , 3.0.0, 3.0.1, ...] 3.2.0
 - Snap Camera Version: [e.g. 1.19, 1.20, 1.21] 1.21
 - Signature Patch applied: [yes or no] yes

Hi, a lot of my lenses placeholder pictures are not loading. I will attach an image of what it shoes for the placeholder image. 
I love your work and appreciate all that you have done for snapcam etc. 
Hope to hear back from you soon, thanks again! 
<img width="142" alt="df3459b88c6b731918e76b2c38d6c903" src="https://github.com/ptrumpis/snap-camera-server/assets/95573944/5657dd12-b56b-4d92-b2c7-7ef15d030563">

**Comment by ptrumpis** [comment]
There was another undocumented change in version 3.2.0.
I forgot to add it to the changelog (I'll update the changelog).

Some Snap lenses do not have a preview image at all and some lenses do not load the image due to a network error.
Before v3.2.0 it was not possible to visually distinguish these two cases.

With v3.2.0, Snap lenses are delivered without preview images with the standard images provided by the server.
These images are located in the server directory under "/nginx/snap-camera-media".
[see here](https://github.com/ptrumpis/snap-camera-server/tree/main/nginx/snap-camera-media)

The images are not particularly beautiful by default, but they clearly stand out.
You are welcome to edit them in your directory.

It would be nice if you could give me 2-3 share links to snap lenses that have the problem.
Then I can check whether these lenses really do not contain their own thumbnail or whether there is a bug.

**Comment by dingerr** [comment]
sure, let me find some. 
https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=681bc9199731473e8b21970e6b7b10b8&metadata=01
https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=859b52f8dc4c45929f530d8026c274f1&metadata=01
https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=cbd6fb0945c24219a00c744a972fe4f0&metadata=01
https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=0716fb48ac8c4d54a9999e5e7623bc7e&metadata=01

**Comment by ptrumpis** [comment]
Thank you, I'll provide a fix shortly

**Comment by dingerr** [comment]
awesome! thanks for the quick response, I really appreciate all you do, and me and my friends use snapcam daily. 
:) 
also please let me know if you ever need any help with testing / beta updates or whatever, I'd be honored to help.

**Comment by dingerr** [comment]
@ptrumpis 
Any luck with finding the root of the issue or a workaround? I am still having / it is showing no placeholder image for almost the majority of my filters. 
Again much appreciated.

**Comment by ptrumpis** [comment]
Resolved with [Patch Release v3.2.1](https://github.com/ptrumpis/snap-camera-server/releases/tag/v3.2.1)
