### ISSUE TITLE
Docker error: Invalid argument, expected lens object

### ISSUE THREAD

**Issue by tinkertims** [ptrumpis/snap-camera-server#84]
Docker throws this error: Invalid argument, expected lens object

**System Information:**
 - OS: Windows 10
 - Snap Camera Version: 1.21
 - Signature Patch applied: yes

**Log:**
[Log.txt](https://github.com/ptrumpis/snap-camera-server/files/13387932/Log.txt)

Lens share link:** https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=bba25a0521164a52bdfc70137d6e18da&metadata=01

**Comment by ptrumpis** [comment]
The lens helped me to discover a bug in [snap lens tool](https://github.com/ptrumpis/snap-lens-tool).

But the real problem here is that this lens is using some assets with an  "unsuported blend mode".
Which will result in log.txt error messages like:

```
Core: Unknown blend mode 
```
```
"Lens not loaded exception: Unknown blend mode"
```

I managed to fix the blend mode manually.
This will be done automatically in the next major release of snap camera server.
And it will be an upcoming feature of [snap lens tool](https://github.com/ptrumpis/snap-lens-tool).

No Filter Active
![No Filter](https://github.com/ptrumpis/snap-camera-server/assets/116500225/6729c574-2ed4-4627-81ee-9018da6b6e10)
Filter Active with Blend Mode (Normal)
![Filter with BlendMode (Normal)](https://github.com/ptrumpis/snap-camera-server/assets/116500225/392c91e7-1c4a-4076-a3a5-ce8d995d7dff)

Here is the fixed lens for download, you would have to manually upload it to server.
[PAEyesBlendFixed.zip](https://github.com/ptrumpis/snap-camera-server/files/13394947/PAEyesBlendFixed.zip)

If you are the creator of the lens, you should be able to switch to another blend mode in lens studio.
And then re-publish the lens.

Here is a list of supported blend modes:

BlendMode | Value | Expression
-- | -- | --
Normal | 0 | SrcAlpha, OneMinusSrcAlpha
MultiplyLegacy [DEPRECATED] | 1 | DstColor, OneMinusSrcAlpha
AddLegacy [DEPRECATED] | 2 | One, One
Screen | 3 | One, OneMinusSrcColor
PremultipliedAlpha | 4 | One, OneMinusSrcAlpha
AlphaToCoverage | 5 | Blend Disabled
Disabled | 6 | Blend Disabled
Add | 7 | SrcAlpha, One
AlphaTest | 8 | Blend Disabled
ColoredGlass | 9 | Blend Disabled
Multiply | 10 | DstColor, Zero
Min | 11 | One, One
Max | 12 | One, One
